export type Category =
  | "ai"
  | "labs"
  | "startups"
  | "business"
  | "events"
  | "tech"
  | "community";

export interface CategoryMeta {
  id: Category;
  label: string;
  emoji: string;
}

/** How a source is fetched.
 *  - "rss": an RSS/Atom feed (default). Tried direct, then via rss2json, then via a CORS proxy.
 *  - Everything else is a public JSON API that sends CORS headers, so the
 *    browser calls it directly with no proxy and no API key. */
export type SourceKind =
  | "rss"
  | "hn-algolia"
  | "hf-models"
  | "hf-papers"
  | "gdelt"
  | "bluesky"
  | "devto"
  | "confs-tech";

export interface FeedSource {
  id: string;
  name: string;
  url: string;
  category: Category;
  kind?: SourceKind;
}

// --- Digest (the editorial briefing generated by scripts/build-digest.ts) ---

/** One cited article. `id` is the [n] used in the bullets. */
export interface DigestSource {
  id: number;
  title: string;
  url: string;
  source: string;
  date: string;
}

export interface DigestItem {
  text: string;
  sources: number[];
}

export interface DigestSection {
  topic: string;
  emoji: string;
  category: Category;
  summary: string;
  items: DigestItem[];
}

export interface Digest {
  id: string;
  generatedAt: string;
  periodStart: string;
  periodEnd: string;
  title: string;
  subtitle: string;
  sections: DigestSection[];
  sources: DigestSource[];
  stats: { posts: number; sourcesOk: number; sourcesFailed: number };
  generator: "claude" | "headlines";
  model?: string;
}

export interface DigestIndexEntry {
  id: string;
  generatedAt: string;
  title: string;
  generator: Digest["generator"];
}

/** A source that returned nothing this cycle, with every attempt's reason. */
export interface FailedSource {
  name: string;
  reason: string;
}

export interface Post {
  id: string;
  title: string;
  link: string;
  description: string;
  pubDate: string;
  source: string;
  sourceId: string;
  sourceCategory: Category;
  tags: Category[];
  imageUrl?: string;
  /** For events: when it happens (ISO date). pubDate stays "when we learned about it". */
  eventDate?: string;
  /** For events: "Buenos Aires, Argentina" or "Online". */
  location?: string;
}
